### ISSUE TITLE
More problems with sidebar height

### ISSUE THREAD

**Issue by jodizzle** [jakebathman/Rocket-Chat-Inverted#4]
It seems like there are still problems lingering with the sidebar height after #1, at least in recent versions of Rocket Chat.  Changing the Y-offsets of the following
```css
.side-nav .rooms-list {
    height: calc(100% - 60px);
}

.account-box .options {
    height: calc(100% - 60px);
}

.flex-nav .content {
    height: calc(100% - 60px);
}
```
from `- 60px` to around `- 100px` seems to have worked for me, but maybe there's a better way?

EDIT:
Here's an example of the bottom left corner, for clarity:
![sidebar_cutoff](https://cloud.githubusercontent.com/assets/672268/25214290/6c340da8-2564-11e7-9e58-c32a0873a7e0.png)
