### ISSUE TITLE
Search background color is blue

### ISSUE THREAD

**Issue by jakebathman** [jakebathman/Rocket-Chat-Inverted#5]
In the latest version of the [Rocket Chat demo](https://demo.rocket.chat), there is a universal search bar at the top of the sidebar.

Need to add this rule to the style:

```css
.toolbar {
    background-color: #171717;
}
```

**Comment by jakebathman** [comment]
Looks like that rule will fix it, but there are other issues with the default blue peeking out (such as during sidebar animation when clicking _More channels..._). 

That color is set using the general rule (with correct dark color): 

```css
.primary-background-color{
  background-color: #171717;
}
```

This should fix the search background and other lingering issues in the sidebar.

**Comment by jakebathman** [comment]
One more place in this search bar is the popover with results (when clicking the search input). Fixed with this snippet:

```css
.message-popup.search-results-list{
  background-color: #0c0c0c;
}
```
