### ISSUE TITLE
Inline code is black on white text

### ISSUE THREAD

**Issue by jodizzle** [jakebathman/Rocket-Chat-Inverted#6]
Looks like this:
![rocketchat_inverted_example_inline_code](https://cloud.githubusercontent.com/assets/672268/25420395/ebd462ea-2a25-11e7-8062-d6724b1effd4.png)
Rocket.Chat v0.53.0.

**Comment by jakebathman** [comment]
Recent change that adds `.code-colors` class to inline. Fix (which is the same as the current `code` element style):

```css
.code-colors {
    background-color: #1f1f1f;
    color: #D4D4D4;
    border-color: #636363;
    font-weight: normal !important;
}
```
