### ISSUE TITLE
Message dropdown menu is transparent

### ISSUE THREAD

**Issue by jakebathman** [jakebathman/Rocket-Chat-Inverted#8]
![Transparent menu](https://cloud.githubusercontent.com/assets/43112/25857766/a5cff582-349f-11e7-9c8f-37b498d3bccd.png)

Thanks to @jarrodldavis for the report

Selector is at `.message .message-dropdown` and background is set here: https://github.com/jakebathman/Rocket-Chat-Inverted/blob/master/RocketChatInverted.css#L190

### Fix

```css
.message .message-dropdown {
    background-color: #171717;
    border: 1px solid #555555;
}
```

Should also change the `:hover` background color on dropdown items to be darker. Change [line #197](https://github.com/jakebathman/Rocket-Chat-Inverted/blob/master/RocketChatInverted.css#L197) to:

```css
.message .message-dropdown ul li:hover, .message .message-dropdown ul li:first-child {
    background-color: #000000;
}
```
